## 회귀모델 사용 
- y(label, 종속변수, target) 가 연속형 일 때 사용

In [25]:
!pip install scikit-learn

In [26]:
import sklearn as sk

### 데이터 수집

In [27]:
from sklearn import datasets 

# from boston house - remove 됨
# from diabetes - 인디언 당뇨 상황 조사
load_diabetes = datasets.load_diabetes()
load_diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [28]:
# feature datas
type(load_diabetes['data']), load_diabetes['data'].shape

(numpy.ndarray, (442, 10))

In [29]:
# label datas
type(load_diabetes['target']), load_diabetes['target'].shape, load_diabetes['target'].dtype

(numpy.ndarray, (442,), dtype('float64'))

In [30]:
# feature names
load_diabetes['feature_names'], type(load_diabetes['feature_names']), len(load_diabetes['feature_names'])

(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], list, 10)

In [31]:
print(load_diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

### 데이터 전처리
- 결측치와 이상치 처리
- 데이터셋 분할 (학습용도와 검증용도)

In [32]:
import pandas as pd

In [33]:
# 원래는 numpy 채로 학습 시킴 pandas로 잘 안바꿈
# feature 처리
df_diabetes = pd.DataFrame(data=load_diabetes['data'],
             columns=load_diabetes['feature_names'],
             )
df_diabetes.head()
# 성별 나이를 std 처리 한 결과 임.

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [34]:
# label 처리
df_diabetes['measure_value'] = load_diabetes['target']
df_diabetes.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  measure_value  
0 -0.002592  0.019907 -0.017646          151.0  
1 -0.039493 -0.068332 -0.092204           75.0  
2 -0.002592  0.002861 -0.025930          141.0  
3  0.034309  0.022688 -0.009362          206.0  
4 -0.002592 -0.031988 -0.046641          135.0

In [35]:
df_diabetes.shape

(442, 11)

In [36]:
df_diabetes.info()    

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   age            442 non-null    float64
 1   sex            442 non-null    float64
 2   bmi            442 non-null    float64
 3   bp             442 non-null    float64
 4   s1             442 non-null    float64
 5   s2             442 non-null    float64
 6   s3             442 non-null    float64
 7   s4             442 non-null    float64
 8   s5             442 non-null    float64
 9   s6             442 non-null    float64
 10  measure_value  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB


In [37]:
# 학습용도와 검증용도 분리

### 데이터 학습 과정 

In [38]:
from sklearn.linear_model import LinearRegression
linearRegression = LinearRegression() 
linearRegression

LinearRegression()

In [39]:
# 넘파이 방식
linearRegression.fit(X=load_diabetes['data'],y=load_diabetes['target'])

LinearRegression()

In [40]:
# dataframe 방식 
# X = df_diabetes.iloc[:,:-1]
# y = df_diabetes['measure_value']
linearRegression.fit(X=df_diabetes.iloc[:,:-1], y=df_diabetes['measure_value'])

LinearRegression()

### 데이터 학습 검증

In [41]:
# 원래는 학습 데이터와 검증 데이터 나누어야해
linearRegression.score(X=load_diabetes['data'],y=load_diabetes['target'])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


0.5177484222203498

In [42]:
# weight와 동일
linearRegression.coef_, len(linearRegression.coef_)
# y = linearRegression.coef_[0] * x1 + ~ + linearRegression.coef_[n] * xn+1 + linearRegression.intercept_

(array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
        -792.17563855,  476.73902101,  101.04326794,  177.06323767,
         751.27369956,   67.62669218]),
 10)

In [43]:
pd.DataFrame(data=linearRegression.coef_, columns=['coef_'], index=load_diabetes['feature_names'])

coef_
age  -10.009866
sex -239.815644
bmi  519.845920
bp   324.384646
s1  -792.175639
s2   476.739021
s3   101.043268
s4   177.063238
s5   751.273700
s6    67.626692

In [44]:
# y 절편, bias 
linearRegression.intercept_

152.13348416289597

In [45]:
# predict 예측
predict_diabetes = linearRegression.predict(load_diabetes['data'][:5])
predict_diabetes

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([206.11667725,  68.07103297, 176.88279035, 166.91445843,
       128.46225834])

In [46]:
load_diabetes['target'][:5]

array([151.,  75., 141., 206., 135.])

In [50]:
# label 과 predict 차이 
from sklearn.metrics import mean_squared_error, r2_score

predict_diabetes = linearRegression.predict(load_diabetes['data'])
len(predict_diabetes), len(load_diabetes['target'])


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


(442, 442)

In [51]:
mean_squared_error(y_true=load_diabetes['target'], y_pred=predict_diabetes)

2859.6963475867506

In [52]:
r2_score(y_true=load_diabetes['target'], y_pred=predict_diabetes)


0.5177484222203498

### 모델 배포

In [48]:
# 배포는 피클방식으로 주어야해?