## 범주형 변환


### onehotencoder
- 컬럼 대상으로 카테고리 수 만큼 행 벡터 작성 
- 행 벡터의 구성은 0,1

In [75]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
data = np.array([['red'],
['green'],
['blue'],
['red']
])

data = np.array([[1],
[3],
[2],
[1]
])

data = np.array([['red',1],
['green',3],
['blue',2],
['red',2]
])



In [76]:
data, data.shape

(array([['red', '1'],
        ['green', '3'],
        ['blue', '2'],
        ['red', '2']], dtype='<U21'),
 (4, 2))

In [77]:
onehotencoder = OneHotEncoder()
onehotencoder.fit(X=data)

OneHotEncoder()

In [78]:
encoded_data = onehotencoder.transform(X=data)
encoded_data.toarray()

array([[0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0.]])

In [79]:
onehotencoder.categories_

[array(['blue', 'green', 'red'], dtype='<U21'),
 array(['1', '2', '3'], dtype='<U21')]

In [80]:
onehotencoder.get_feature_names_out(input_features=['Color','Num'])

array(['Color_blue', 'Color_green', 'Color_red', 'Num_1', 'Num_2',
       'Num_3'], dtype=object)

#### label encode 
- 대상이 feature 인 경우 : 해당 컬럼 카테고리가 2개 이하 적용 가능
- 대상이 label 인 경우 : 해당 컬럼이 문자인 경우 적용

In [81]:
import pandas as pd

# Titanic 데이터셋 로드 (예제) 
data = { 
    'PassengerId': [1, 2, 3, 4, 5], 
    'Sex': ['male', 'female', 'female', 'male', 'male'] }

df_data = pd.DataFrame(data)
df_data.head()

PassengerId     Sex
0            1    male
1            2  female
2            3  female
3            4    male
4            5    male

In [82]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
labelencoder.fit(df_data['Sex'])

LabelEncoder()

In [83]:
encoded_label = labelencoder.transform(df_data['Sex'])
encoded_label # labelencoder.classes_의 index 값을 매김김

array([1, 0, 0, 1, 1])

In [84]:
labelencoder.classes_

array(['female', 'male'], dtype=object)

In [85]:
import pandas as pd

# Titanic 데이터셋 로드 (예제) 
data = { 
    'PassengerId': [1, 2, 3, 4, 5], 
    'Sex': ['male', 'female', 'rand', 'male', 'male'] }

df_data = pd.DataFrame(data)
df_data.head()

PassengerId     Sex
0            1    male
1            2  female
2            3    rand
3            4    male
4            5    male

In [86]:
labelencoder = LabelEncoder()
labelencoder.fit(df_data['PassengerId'])

LabelEncoder()

In [87]:
labelencoder.classes_


array([1, 2, 3, 4, 5])

In [88]:
encoded_label = labelencoder.transform(df_data['PassengerId'])
encoded_label

array([0, 1, 2, 3, 4])

In [89]:
import pandas as pd

# Titanic 데이터셋 로드 (예제) 
data = { 
    'PassengerId': [1, 2, 3, 4, 5], 
    'Sex': ['male', 'female', 'rand', 'male', 'male'] ,
    'Char': ['C', 'Q', 'S', 'C', 'X']
    }

df_data = pd.DataFrame(data)
df_data.head()

PassengerId     Sex Char
0            1    male    C
1            2  female    Q
2            3    rand    S
3            4    male    C
4            5    male    X

In [91]:
labelencoder = LabelEncoder()
labelencoder.fit(df_data['Char'])

LabelEncoder()

In [92]:
labelencoder.classes_


array(['C', 'Q', 'S', 'X'], dtype=object)

In [94]:
encoded_label = labelencoder.transform(df_data['Char'])
encoded_label

array([0, 1, 2, 0, 3])